apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapid-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapid-app
  template:
    metadata:
      labels:
        app: rapid-app
    spec:
      containers:
      - name: rapid-app-container
        image: dohitdeegwal/rapid-app:__TAG__
        ports:
        - containerPort: 5000
