name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      with:
        version: '443.0.0'  # Use the latest version
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/rapid-app:$GITHUB_SHA .
        docker push ${{ secrets.DOCKER_USERNAME }}/rapid-app:$GITHUB_SHA
      env:
        GITHUB_SHA: ${{ github.sha }}

    - name: Deploy to GKE
      run: |
        # Authenticate with Google Cloud
        echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > key.json
        gcloud auth activate-service-account --key-file=key.json

        # Set up Kubernetes credentials
        gcloud container clusters get-credentials rapid-cluster --zone asia-south2 --project ${{ secrets.GCP_PROJECT_ID }}

        # Apply Kubernetes deployment and service configuration
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GITHUB_SHA: ${{ github.sha }}
