name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        version: '343.0.0'  # Use the latest version
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GKE
      run: |
        # Set up Kubernetes credentials
        gcloud container clusters get-credentials rapid-cluster --zone asia-south2 --project ${{ secrets.GCP_PROJECT_ID }}

        # Apply Kubernetes deployment and service configuration
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
